import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Locale, i18n } from '@/src/utils/i18n.config'
import 'bootstrap/dist/css/bootstrap.min.css';

import './globals.css'

import Header from './components/Header';
import Footer from './components/Footer';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Miras Education',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18n.locales.map(locale => ({ lang: locale }))
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode
  params: { lang: Locale }
})  {
  return (
    <html lang={params.lang}>
      <body className={inter.className}>
          <div className="wrap">
          <Header lang={params.lang}/> 
            <div className='content'>
            {children}
            </div>
           <Footer/> 
          </div>
        </body>
    </html>
  )
}
